name: EasyVillagers
version: '1.0-SNAPSHOT'
main: xyz.berrystudios.easyvillagers.EasyVillagers
api-version: '1.20'
authors: [ Anthony M. ]
description: A plugin based on the EasyVillagers modpack
depend:
  - packetevents